#!/bin/sh

echo 'Reponame?'
read reponame

echo 'Username?'
read username

test -z $reponame && echo "Repo name required." 1>&2 && exit 1

curl -u '$username' https://api.github.com/user/repos -d '{"name":"$reponame"}'

git remote add https://$username@github.com/$reponame.git

git push -u origin --all
