#!/bin/sh

echo 'Reponame?'
read reponame

echo 'Username?'
read username

echo 'Password?'
read -s password

curl -u $username:$password https://api.github.com/user/repos -d "{\"name\":\"$reponame\"}"

echo \# README > README.md | echo \#\# $reponame >> README.md

git remote add origin https://$username@github.com/$reponame.git

git add . && git commit -m "first"

git push -u origin --all