#!/bin/sh

read -p 'Project name:' repo_name

PS3='Please enter your choice:'
options=("neuro-oncologia" "tumor-snc" "fhcflx-publications" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "neuro-oncologia")
            id=758202
            ;;
        "tumor-snc")
            id=758202
            ;;
        "fhcflx-publications")
            id=704563
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done

read -p 'Visibility (true/false):' visibility

token=syssiUSiZwZyV4sN8zP9

test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl --header "private-token:$token" -X POST "https://gitlab.com/api/v3/projects?name=$repo_name&namespace_id=$id&public=$visibility"
