#!/bin/sh

read -p 'Project name:' repo_name

PS3='Please enter your choice:'
options=("neuro-oncologia" "oncologiaped" "fhcflx-publications" "fhcflx-meetings" "fhcflx-projects" "prepub" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "neuro-oncologia")
            id=758202
            break
            ;;
        "oncologiaped")
            id=704563
            break
            ;;
        "fhcflx-publications")
            id=758207
            break
            ;;
        "fhcflx-meetings")
            id=1089140
            break
            ;;
        "fhcflx-projects")
            id=1098050
            break
            ;;
        "prepub")
            id=1087522
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option
            ;;
    esac
done

read -p 'Visibility (true/false):' visibility

token=syssiUSiZwZyV4sN8zP9

test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl --header "private-token:$token" -X POST "https://gitlab.com/api/v3/projects?name=$repo_name&namespace_id=$id&public=$visibility"
